# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Prework"
  url = "prework"
  weight = 10
  
[[main]]
  name = "Schedule"
  url = "#schedule"
  weight = 20

[[main]]
  name = "Logistics"
  url = "#logistics"
  weight = 30

[[main]]
  name = "Materials"
  url = "#materials"
  weight = 40

[[main]]
  name = "Code of Conduct"
  url = "#code_of_conduct"
  weight = 50

[[main]]
  name = "People"
  url = "#people"
  weight = 60
  
[[main]]
  name = "Resources"
  url = "resources"
  weight = 70
  
[[main]]
  pre = "<i class=\"fab fa-github fa-lg\"></i>"
  name = ""
  url = "https://github.com/uopsych/summeR-bootcamp-2020"
  weight = 80
  


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
