[build]
  publish = "public/"
  command = "hugo"
  
[build.environment]
  HUGO_VERSION = "0.65.0"

[context.production.environment]
  publish = "public/"
  HUGO_VERSION = "0.65.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
  publish = "public/"
  HUGO_VERSION = "0.65.0"

[context.deploy-preview.environment]
  publish = "public/"
  HUGO_VERSION = "0.65.0"

[context.deploy-preview]
  publish = "public/"
  command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"

[context.branch-deploy]
  publish = "public/"
  command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"
